version: '3.3'

services:
  goldendays:
    build:
      dockerfile: Dockerfile
    volumes:
     - ./database.db:/app/database.db
     


  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - goldendays
    restart: always
    environment:
      DOMAINS: 'cphgoldendays.org -> http://goldendays:8000'
      STAGE: production
    volumes:
      - ./tls-certs:/var/lib/https-portal